const FETCH_THONG_TIN_PHIM_REQUESTS =
  "fetch_thong_tin/FETCH_THONG_TIN_PHIM_REQUESTS";
const FETCH_THONG_TIN_PHIM_SUCCESS =
  "fetch_thong_tin/FETCH_THONG_TIN_PHIM_SUCCESS";
const FETCH_THONG_TIN_PHIM_FAILED =
  "fetch_thong_tin/FETCH_THONG_TIN_PHIM_FAILED";
